---
image: python:2.7

services:
  - name: docker.local.intelions.ru/docker:dind
    alias: docker

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

#    - .cache/venv/
#  - pip install virtualenv
#  - virtualenv .cache/venv
#  - source .cache/venv/bin/activate
#  - curl -sSlo requirements.txt
before_script:
  - python -V               # Print out python version for debugging
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - molecule --version
    - ansible --version
    - molecule test -s default
