---
image: python:2.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - name: docker.local.intelions.ru/docker:dind
    alias: docker

cache:
  paths:
    - .cache/pip

#    - .cache/venv/
#  - pip install virtualenv
#  - virtualenv .cache/venv
#  - source .cache/venv/bin/activate
#  - curl -sSlo requirements.txt
before_script:
  - pip install -r requirements.txt
  - apt-get install docker-ce
  - ls -lah /var/run/
  - ping -c 3 docker

test:
  stage: test
  script:
    - pwd
    - ls -lah ./
    - echo $PATH
    - python -V
    - molecule --version
    - ansible --version
    - molecule test -s default
