---
image: docker.local.intelions.ru/python/python2.7-docker

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - name: docker.local.intelions.ru/docker:dind
    alias: docker

cache:
  paths:
    - .cache/pip
    - .cache/venv/

#  - curl -sSlo requirements.txt
before_script:
  - virtualenv .cache/venv
  - source .cache/venv/bin/activate
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - docker info
    - python -V
    - molecule --version
    - ansible --version
    - molecule test -s default
