---
sudo: required
language: python
services:
  - docker

addons:
  hosts:
    - centos

install:
  - pip install -r requirements.txt

script:
  - docker info
  - python -V
  - molecule --version
  - ansible --version
  - molecule test -s default
