---

- name: "Set package manager"
  set_fact:
    etck_highlevel_package_manager: yum
    etck_lowlevel_package_manager: rpm
  when:
    - ansible_os_family == "RedHat"
    - ansible_pkg_mgr == "yum"

- name: "Set package manager"
  set_fact:
    etck_highlevel_package_manager: apt
    etck_lowlevel_package_manager: dpkg
  when:
    - ansible_os_family == "Debian"
    - ansible_pkg_mgr == "apt"

- name: Configure etckeeper.conf
  template:
    src: etckeeper_conf.j2
    dest: /etc/etckeeper/etckeeper.conf
    mode: 0640
    owner: root
    group: root

- name: Check git directory
  stat:
    path: /etc/.git
  register: etck_stat_result
  changed_when: not etck_stat_result.stat.exists
  notify: etckeeper init

- name: Check clean directory
  command: etckeeper unclean
  register: etck_unclean
  ignore_errors: True
  changed_when: "etck_unclean.rc == 0"
  notify: etckeeper commit
