---

- name: Block Install CentOS 7
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  block:
  - name: Install packages
    yum:
      name:
      - etckeeper
      - git
      state: present
    notify: etckeeper init

- meta: flush_handlers

