---

- name: Block Install CentOS 
  when: ansible_os_family == "RedHat" and ansible_pkg_mgr == "yum"
  block:
  - name: Install packages
    yum:
      name:
      - etckeeper
      - git
      state: present
    notify: etckeeper init

- name: Block Install Ubuntu
  when: ansible_os_family == "Debian" and ansible_pkg_mgr == "apt"
  block:
  - name: Install packages
    apt:
      name:
      - etckeeper
      - git
      state: present
    notify: etckeeper init

