---

- name: Check OS compatable
  fail: msg="Role not compatable"
  when:
  - ansible_distribution != "CentOS" or ansible_distribution_major_version != "7"
  tags: check

# CentOS specific package installations
- import_tasks: install.yml
  become: true
  tags: install

# Configure
- import_tasks: configure.yml
  become: true
  tags: configure


