---

- name: Check OS compatable
  fail: msg="Role not compatable"
  when:
  - ansible_os_family != "RedHat" 
  - ansible_os_family != "Debian"
  tags: check

# CentOS specific package installations
- import_tasks: install.yml
  become: true
  tags: install

# Configure
- import_tasks: configure.yml
  become: true
  tags: configure


